
export const data = [
    {
        authorName: "Mouhammed Ramadan",
        releaseDate: "05-04-2018",
        authorThumbnail: "https://asset.lemde.fr/prd-blogs/2020/08/4871d278-500x500.jpg",
        title: "Ensay",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        song: "https://www.youtube.com/embed/q0hyYWKXF0Q",
        index: 0,
    },
    {
        authorName: "Algerino",
        releaseDate: "05-04-2016",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnjfnBernOsr-DtVdc7e36CBqLMSXFM2XYNo1UWpKA=s900-c-k-c0x00ffffff-no-rj",
        title: "Les Menottés",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        song: "https://www.youtube.com/embed/Fvw4vOXyBPU",
        index: 1,
    },
    {
        authorName: "Soolking",
        releaseDate: "05-04-2015",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnj4HLk3lz0GKqDbonRrJWBgxCLgc4-i4csV2Lmmwg=s900-c-k-c0x00ffffff-no-rj",
        title: "Guerilla",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        song: "https://www.youtube.com/embed/YLIWleB0g78",
        index: 2,
    },
    {
        authorName: "L'artiste",
        releaseDate: "05-04-2017",
        authorThumbnail: "https://i.ytimg.com/vi/S6baf8BqKDI/maxresdefault.jpg",
        title: "Mafiosa",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        song: "https://www.youtube.com/embed/S6baf8BqKDI",
        index: 3,
    },
    {
        authorName: "Tones And I",
        releaseDate: "05-04-2019",
        authorThumbnail: "https://www.rollingstone.com/wp-content/uploads/2020/05/TONES-and-I-RS-option-1.jpg",
        title: "Mafiosa",
        song: "https://www.youtube.com/embed/q0hyYWKXF0Q",
        index: 4,
    },
]

