
export const data = [
    {
        authorName: "Mouhammed Ramadan",
        releaseDate: "05-04-2018",
        authorThumbnail: "https://asset.lemde.fr/prd-blogs/2020/08/4871d278-500x500.jpg",
        title: "Ensay",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/7iSJbEUuRnE/maxresdefault.jpg",
        index: 0,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "2,421,444"
    },
    {
        authorName: "Algerino",
        releaseDate: "05-04-2016",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnjfnBernOsr-DtVdc7e36CBqLMSXFM2XYNo1UWpKA=s900-c-k-c0x00ffffff-no-rj",
        title: "Les Menottés",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/Fvw4vOXyBPU/maxresdefault.jpg",
        index: 1,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "3,540,121"
    },
    {
        authorName: "Soolking",
        releaseDate: "05-04-2015",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnj4HLk3lz0GKqDbonRrJWBgxCLgc4-i4csV2Lmmwg=s900-c-k-c0x00ffffff-no-rj",
        title: "Guerilla",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/YLIWleB0g78/maxresdefault.jpg",
        index: 2,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "421,444"
    },
    {
        authorName: "L'artiste",
        releaseDate: "05-04-2017",
        authorThumbnail: "https://i.ytimg.com/vi/S6baf8BqKDI/maxresdefault.jpg",
        title: "Mafiosa",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://static.hotmixradio.fr/wp-content/uploads/LARTISTE-Mafiosa.jpg",
        index: 3,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "6,421,200"
    },
    {
        authorName: "Tones And I",
        releaseDate: "05-04-2019",
        authorThumbnail: "https://www.rollingstone.com/wp-content/uploads/2020/05/TONES-and-I-RS-option-1.jpg",
        title: "Mafiosa",
        thumbnail: "https://i.ytimg.com/vi/q0hyYWKXF0Q/maxresdefault.jpg",
        index: 4,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "1,124,101"
    },
    {
        authorName: "Mouhammed Ramadan",
        releaseDate: "05-04-2018",
        authorThumbnail: "https://asset.lemde.fr/prd-blogs/2020/08/4871d278-500x500.jpg",
        title: "Ensay",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/7iSJbEUuRnE/maxresdefault.jpg",
        index: 5,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "2,421,444"
    },
    {
        authorName: "Algerino",
        releaseDate: "05-04-2016",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnjfnBernOsr-DtVdc7e36CBqLMSXFM2XYNo1UWpKA=s900-c-k-c0x00ffffff-no-rj",
        title: "Les Menottés",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/Fvw4vOXyBPU/maxresdefault.jpg",
        index: 6,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "3,540,121"
    },
    {
        authorName: "Soolking",
        releaseDate: "05-04-2015",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnj4HLk3lz0GKqDbonRrJWBgxCLgc4-i4csV2Lmmwg=s900-c-k-c0x00ffffff-no-rj",
        title: "Guerilla",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/YLIWleB0g78/maxresdefault.jpg",
        index: 7,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "421,444"
    },
    {
        authorName: "L'artiste",
        releaseDate: "05-04-2017",
        authorThumbnail: "https://i.ytimg.com/vi/S6baf8BqKDI/maxresdefault.jpg",
        title: "Mafiosa",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://static.hotmixradio.fr/wp-content/uploads/LARTISTE-Mafiosa.jpg",
        index: 8,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "6,421,200"
    },
    {
        authorName: "Tones And I",
        releaseDate: "05-04-2019",
        authorThumbnail: "https://www.rollingstone.com/wp-content/uploads/2020/05/TONES-and-I-RS-option-1.jpg",
        title: "Mafiosa",
        thumbnail: "https://i.ytimg.com/vi/q0hyYWKXF0Q/maxresdefault.jpg",
        index: 9,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "1,124,101"
    },
    {
        authorName: "Mouhammed Ramadan",
        releaseDate: "05-04-2018",
        authorThumbnail: "https://asset.lemde.fr/prd-blogs/2020/08/4871d278-500x500.jpg",
        title: "Ensay",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/7iSJbEUuRnE/maxresdefault.jpg",
        index: 10,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "2,421,444"
    },
    {
        authorName: "Algerino",
        releaseDate: "05-04-2016",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnjfnBernOsr-DtVdc7e36CBqLMSXFM2XYNo1UWpKA=s900-c-k-c0x00ffffff-no-rj",
        title: "Les Menottés",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/Fvw4vOXyBPU/maxresdefault.jpg",
        index: 11,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "3,540,121"
    },
    {
        authorName: "Soolking",
        releaseDate: "05-04-2015",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnj4HLk3lz0GKqDbonRrJWBgxCLgc4-i4csV2Lmmwg=s900-c-k-c0x00ffffff-no-rj",
        title: "Guerilla",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/YLIWleB0g78/maxresdefault.jpg",
        index: 12,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "421,444"
    },
    {
        authorName: "L'artiste",
        releaseDate: "05-04-2017",
        authorThumbnail: "https://i.ytimg.com/vi/S6baf8BqKDI/maxresdefault.jpg",
        title: "Mafiosa",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://static.hotmixradio.fr/wp-content/uploads/LARTISTE-Mafiosa.jpg",
        index: 13,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "6,421,200"
    },
    {
        authorName: "Tones And I",
        releaseDate: "05-04-2019",
        authorThumbnail: "https://www.rollingstone.com/wp-content/uploads/2020/05/TONES-and-I-RS-option-1.jpg",
        title: "Mafiosa",
        thumbnail: "https://i.ytimg.com/vi/q0hyYWKXF0Q/maxresdefault.jpg",
        index: 14,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "1,124,101"
    },
    {
        authorName: "Mouhammed Ramadan",
        releaseDate: "05-04-2018",
        authorThumbnail: "https://asset.lemde.fr/prd-blogs/2020/08/4871d278-500x500.jpg",
        title: "Ensay",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/7iSJbEUuRnE/maxresdefault.jpg",
        index: 15,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "2,421,444"
    },
    {
        authorName: "Algerino",
        releaseDate: "05-04-2016",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnjfnBernOsr-DtVdc7e36CBqLMSXFM2XYNo1UWpKA=s900-c-k-c0x00ffffff-no-rj",
        title: "Les Menottés",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/Fvw4vOXyBPU/maxresdefault.jpg",
        index: 16,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "3,540,121"
    },
    {
        authorName: "Soolking",
        releaseDate: "05-04-2015",
        authorThumbnail: "https://yt3.ggpht.com/ytc/AAUvwnj4HLk3lz0GKqDbonRrJWBgxCLgc4-i4csV2Lmmwg=s900-c-k-c0x00ffffff-no-rj",
        title: "Guerilla",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://i.ytimg.com/vi/YLIWleB0g78/maxresdefault.jpg",
        index: 17,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "421,444"
    },
    {
        authorName: "L'artiste",
        releaseDate: "05-04-2017",
        authorThumbnail: "https://i.ytimg.com/vi/S6baf8BqKDI/maxresdefault.jpg",
        title: "Mafiosa",
        likes: 2540,
        dislikes: 200,
        comments: 1540,
        thumbnail: "https://static.hotmixradio.fr/wp-content/uploads/LARTISTE-Mafiosa.jpg",
        index: 18,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "6,421,200"
    },
    {
        authorName: "Tones And I",
        releaseDate: "05-04-2019",
        authorThumbnail: "https://www.rollingstone.com/wp-content/uploads/2020/05/TONES-and-I-RS-option-1.jpg",
        title: "Mafiosa",
        thumbnail: "https://i.ytimg.com/vi/q0hyYWKXF0Q/maxresdefault.jpg",
        index: 19,
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        views: "1,124,101"
    },
]

